CREATE TABLE IF NOT EXISTS category (id INTEGER PRIMARY KEY, name VARCHAR(100), description VARCHAR(2000), age_group VARCHAR(20), created TIMESTAMP, inserted BIGINT);

CREATE TABLE IF NOT EXISTS "LEGO_SET" (id INTEGER, name VARCHAR(100), "MIN_AGE" INTEGER, "MAX_AGE" INTEGER);
CREATE TABLE IF NOT EXISTS "HANDBUCH" ("HANDBUCH_ID" INTEGER, author VARCHAR(100), text TEXT);
CREATE TABLE IF NOT EXISTS "MODEL" ("NAME" VARCHAR(100), description TEXT, lego_set INTEGER);
